### ISSUE TITLE
more or less random suggestions

### ISSUE THREAD

**Issue by migueldiascosta** [easybuilders/easybuild-tutorial#19]
- [ ] as an "appetizer", let people install something simple at the end of "Practical information" ?
- [ ] mention `--dump-env-script` in "Inspecting the build directory" ?
- [ ] mention how to handle multiple architectures in "Configuration" ?
- [ ] mention `--subdir-user-modules` when talking about HMNS and "Stacking software" ?

**Comment by boegel** [comment]
I consider most of these out of scope for the tutorial, we can't cover everything.

As appetizer, I think we can let people do a quick install after properly configuring EasyBuild (see #27), I wouldn't let them install stuff in the default `$HOME/.local/easybuild` location?

**Comment by boegel** [comment]
Quick install of `bzip2` after configuring is done, so I'll close this...
