### ISSUE TITLE
Still more in "Adding support..."

### ISSUE THREAD

**Issue by akesandgren** [easybuilders/easybuild-tutorial#49]
In the eb-tutorial "Sanity check" section:
"Let us now retry, but use --module-only rather than redoing the whole installation."

This may warrant a more detailed explanation and reminding the reader what actually happened.
I.e. that the installation was actually done, and clarifying that --module-only runs the sanity check and creates the module.

This is still fairly early on...

**Comment by boegel** [comment]
fixed in #52
